// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/index.tsx";
import * as $$0 from "./islands/AddToCart.tsx";
import * as $$1 from "./islands/Cart.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/IslandIndicatorSwitch.tsx";
import * as $$4 from "./islands/SynchronizedSlider.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
  },
  islands: {
    "./islands/AddToCart.tsx": $$0,
    "./islands/Cart.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/IslandIndicatorSwitch.tsx": $$3,
    "./islands/SynchronizedSlider.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
